### ISSUE TITLE
Plugin Future

### ISSUE THREAD

**Issue by mikehatfield** [zviryatko/menu-image#10]
Hi there,

I noticed that the plugin is no longer listed or discoverable on the WordPress plugin directory.  

https://wordpress.org/plugins/menu-image/

The support forum still exists however and I see here on github you have made recent updates.  Not being easily discoverable however is going to stop new WordPress devs & users from finding it and limit its user base growth.  What was the reason for this?  Also do you plan on continuing to develop the plugin?  Is there a better alternative available?

I used menu-image on a site and it has worked great thus far.  I'd just like to know your future plans for it before adding to a new theme.

Thanks for all your work!

**Comment by zviryatko** [comment]
Hello,

For you information I will continue develop this plugin, but it temporary blocked by guys from wporg security team, but don't worry, it not contain any vulnerabilities, only has not a perfect agreement on first install. So I'll fix it in near time and submit to approve, I hope plugin will be accessible in next week or so.

**Comment by zviryatko** [comment]
Update: I've removed "malware" and have send to approve, in near time plugin should back again!

**Comment by zviryatko** [comment]
Update 2: It's alive! Closing this ticket.
