### ISSUE TITLE
throws warning and menu image v 2.9.0 issue

### ISSUE THREAD

**Issue by FVDDEV** [zviryatko/menu-image#15]
Hello,
I did exactly what you asked to correct the code. still the issue is same . can you please help me out with the same. here is the link of my website. you can check the warning there.
site url : http://pbsgrouplondon.com/

error : Warning: Missing argument 4 for Menu_Image_Plugin::menu_image_nav_menu_link_attributes_filter() in /home4/abhi2118/public_html/wp-content/plugins/menu-image/menu-image.php on line 271

**Comment by zviryatko** [comment]
Hello, if you download dev version from github then it should be fixed, since 4th argument now optional https://github.com/zviryatko/menu-image/blob/master/menu-image.php#L279

**Comment by FVDDEV** [comment]
Thanks for fixing the issue by the new updates.
